name: Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 60
